### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by newzealandpaul** [tkhadimullin/contact-energy-nz#10]
The README mentions Home Assistant, is there any HA integration that uses this library or official advice on how to push contact energy data into HA using this library?

The custom component https://github.com/codyc1515/ha-contact-energy does not seem to work nor uses this library.

**Comment by tkhadimullin** [comment]
Ther was an integration that I planned to push into HA core: https://github.com/home-assistant/core/pull/91349 but I unfortunately could not get it across the line. At this stage I don't have bandwidth to attempt it again. 

You probably could use the code from there as reference to get the sensor going.

**Comment by newzealandpaul** [comment]
@tkhadimullin Thanks for letting me know. I certainly understand why you would run out of steam.

Maybe in the future HACS would be a better fit: https://www.hacs.xyz/
