### ISSUE TITLE
Reviving the project

### ISSUE THREAD

**Issue by reylinux** [tkhadimullin/contact-energy-nz#5]
Hi, I just bought the Home Assistant Green and enjoying it so far. I would love to get our energy consumption integrated as well to the dashboard. Can you please revive this project or pop the integration to HACS if that's easier? Many thanks!

**Comment by tkhadimullin** [comment]
Thank you for your interest in this project. 
It’s unlikely I’ll make another attempt to open a PR into HA core as I found the process to be too time consuming. HACS is probably still on the table, although I can’t give you any timelines.

You are however welcome to submit PRs from your end and reference this library.
