### ISSUE TITLE
Check API key update

### ISSUE THREAD

**Issue by cloudy-sfu** [tkhadimullin/contact-energy-nz#6]
https://github.com/tkhadimullin/contact-energy-nz/blob/fee8696ff5c50a07ea91844106e2a07ab2298624/contact_energy_nz/consts.py#L2

I know currently, it is a good way to manually check the API key because it will not update frequently. (It hasn't changed for at least the last 2 months.) However, since `<hash>` in JS filename is really random, is there a way to automatically grab any updates?

**Comment by tkhadimullin** [comment]
I presume you could get `index.html`, scan it for `<script>` tags and see which one links to `main.<hash>.esm.js` and then get the script itself?
